version: '3.10'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./sd_discord_bot.sqlite:/app/sd_discord_bot.sqlite
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SD_API_HOST=${SD_API_HOST}
      - DISCORD_GUILDID=${DISCORD_GUILDID}
    command: -token ${DISCORD_TOKEN} -host ${SD_API_HOST} -guild ${DISCORD_GUILDID}
